import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { Modal, Image, Tag, Space, Card, Row, Col, Typography, Carousel, Tabs, } from "antd";
import { ShoppingCartOutlined, TagOutlined, InfoCircleOutlined, FileTextOutlined, PlayCircleOutlined, } from "@ant-design/icons";
import './ProductView.css';
const { Title, Paragraph, Text } = Typography;
export const ProductView = ({ open, onClose, product }) => {
    const [selectedImage, setSelectedImage] = React.useState(null);
    const [previewVisible, setPreviewVisible] = React.useState(false);
    const statusColor = product.active ? "green" : "red";
    const stockColor = product.stock > 10 ? "green" : product.stock > 0 ? "orange" : "red";
    const formatPrice = (price) => {
        return price?.toLocaleString("es-CO", {
            style: "currency",
            currency: "COP",
            minimumFractionDigits: 0,
        });
    };
    return (_jsxs(Modal, { title: null, open: open, onCancel: onClose, width: 1000, footer: null, className: "product-view-modal", children: [_jsxs(Row, { gutter: [24, 24], children: [_jsx(Col, { span: 24, children: _jsx(Card, { className: "header-card", bordered: false, children: _jsxs(Row, { align: "middle", justify: "space-between", children: [_jsxs(Col, { children: [_jsx(Title, { level: 4, style: { margin: 0 }, children: product.name }), _jsxs(Text, { type: "secondary", children: ["SKU: ", product.code] })] }), _jsx(Col, { children: _jsxs(Space, { children: [_jsx(Tag, { color: statusColor, className: "status-tag", children: product.active ? "Activo" : "Inactivo" }), _jsxs(Tag, { color: stockColor, icon: _jsx(ShoppingCartOutlined, {}), children: ["Stock: ", product.stock] })] }) })] }) }) }), _jsx(Col, { xs: 24, md: 12, children: _jsxs(Card, { bordered: false, className: "images-card", children: [_jsx(Carousel, { autoplay: true, children: product.images.map((image, index) => (_jsx("div", { children: _jsx(Image, { src: image, alt: `${product.name} - ${index + 1}`, className: "main-image", preview: false, onClick: () => {
                                                setSelectedImage(image);
                                                setPreviewVisible(true);
                                            } }) }, index))) }), _jsx("div", { className: "thumbnail-container", children: _jsx(Space, { children: product.images.map((image, index) => (_jsx(Image, { src: image, alt: `thumbnail-${index}`, width: 60, height: 60, className: "thumbnail", preview: false, onClick: () => {
                                                setSelectedImage(image);
                                                setPreviewVisible(true);
                                            } }, index))) }) })] }) }), _jsx(Col, { xs: 24, md: 12, children: _jsx(Card, { bordered: false, className: "details-card", children: _jsxs(Space, { direction: "vertical", size: "large", style: { width: "100%" }, children: [_jsxs("div", { children: [_jsxs(Title, { level: 5, children: [_jsx(TagOutlined, {}), " Precio"] }), _jsx(Title, { level: 3, type: "success", style: { margin: 0 }, children: formatPrice(product.price) }), product.old_price && (_jsx(Text, { delete: true, type: "secondary", style: { fontSize: 16 }, children: formatPrice(product.old_price) }))] }), _jsxs("div", { children: [_jsxs(Title, { level: 5, children: [_jsx(InfoCircleOutlined, {}), " Clasificaci\u00F3n"] }), _jsxs(Space, { direction: "vertical", children: [_jsxs(Text, { children: [_jsx("strong", { children: "Grupo:" }), " ", product.group] }), _jsxs(Text, { children: [_jsx("strong", { children: "Subgrupo:" }), " ", product.subgroup] })] })] }), _jsxs("div", { children: [_jsx(Title, { level: 5, children: "M\u00E9todos de Env\u00EDo" }), _jsx(Space, { wrap: true, children: product.shipping.map((method) => (_jsx(Tag, { color: "blue", children: method }, method))) })] })] }) }) }), _jsx(Col, { span: 24, children: _jsx(Card, { bordered: false, className: "description-card", children: _jsxs(Tabs, { defaultActiveKey: "1", children: [_jsx(Tabs.TabPane, { tab: _jsxs("span", { children: [_jsx(FileTextOutlined, {}), " Descripci\u00F3n"] }), children: _jsxs("div", { className: "description-content", children: [_jsx(Paragraph, { strong: true, children: product.short_description }), _jsx("div", { dangerouslySetInnerHTML: {
                                                        __html: product.long_description,
                                                    } })] }) }, "1"), product.videoUrl && (_jsx(Tabs.TabPane, { tab: _jsxs("span", { children: [_jsx(PlayCircleOutlined, {}), " Video"] }), children: _jsx("iframe", { src: product.videoUrl, title: "Product Video", width: "100%", height: "400", frameBorder: "0", allowFullScreen: true }) }, "2")), _jsx(Tabs.TabPane, { tab: _jsxs("span", { children: [_jsx(InfoCircleOutlined, {}), " SEO"] }), children: _jsxs(Space, { direction: "vertical", size: "large", style: { width: "100%" }, children: [_jsxs("div", { children: [_jsx(Text, { strong: true, children: "T\u00EDtulo SEO:" }), _jsx(Paragraph, { children: product.seo?.title || product.name })] }), _jsxs("div", { children: [_jsx(Text, { strong: true, children: "Descripci\u00F3n SEO:" }), _jsx(Paragraph, { children: product.seo?.description || product.short_description })] }), _jsxs("div", { children: [_jsx(Text, { strong: true, children: "Palabras clave:" }), _jsx("div", { children: product.seo?.keywords.map((keyword, index) => (_jsx(Tag, { children: keyword }, index))) })] })] }) }, "3")] }) }) })] }), _jsx(Modal, { open: previewVisible, footer: null, onCancel: () => setPreviewVisible(false), width: 900, className: "image-preview-modal", children: _jsx(Image, { alt: "Preview", src: selectedImage || "", style: { width: "100%" }, preview: false }) })] }));
};
